version: '3'

services:
  db:
    container_name: az_postgres
    image: postgres:9.6.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=actorfilm
